=== PhiSyX/cfoulatech/json/$schema/exo03_schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"type": "object",
	"properties": {
		"sentences": {
			"type": "array",
			"items": {
				"type": "string",
				"minLength": 10,
				"maxLength": 15
			}
		},
		"notes": {
			"type": "array",
			"items": {
				"type": "number",
				"minimum": 0,
				"maximum": 100
			},
			"minItems": 5,
			"maxItems": 10
		},
		"mots": {
			"type": "array",
			"items": {
				"type": "string",
				"pattern": "^[A-Z][a-zA-Z]{5,6}$"
			},
			"minItems": 5,
			"maxItems": 5,
			"uniqueItems": true
		},
		"nombres": {
			"type": "array",
			"items": {
				"type": "number"
			},
			"contains": {
				"type": "integer",
				"minimum": -7,
				"maximum": -7
			}
		},
		"person": {
			"type": "array",
			"prefixItems": [
				{
					"type": "integer",
					"minimum": 1,
					"title": "ID"
				},
				{
					"type": "string",
					"pattern": "^[A-Z][a-zA-Z]+\\s[A-Z][a-zA-Z]+$",
					"description": "Prénom et nom de la personne"
				},
				{
					"type": "string",
					"format": "email",
					"description": "Adresse e-mail de la personne"
				},
				{
					"type": "string",
					"format": "date",
					"title": "Date de naissance",
					"description": "Date de naissance de la personne"
				},
				{
					"type": "boolean",
					"title": "Status maritale",
					"description": "Répondre par oui ou non"
				}
			]
		}
	}
}

=== PhiSyX/cfoulatech/json/$schema/exo03_instance.json
{
	"$schema": "exo03_schema.json",
	"sentences": [
		"bonjour Mike"
	],
	"notes": [
		1,
		2,
		3,
		4,
		5
	],
	"mots": [
		"Bonjour",
		"Bonsoir",
		"Carina",
		"Clovis",
		"Ericou"
	],
	"nombres": [
		1,
		-3.7,
		-7
	],
	"person": [
		1,
		"John Doe",
		"john@doe.fr",
		"1991-12-07",
		true
	]
}
